# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bIW5QiUZKAWwjrc93QZtX-lr7FhQxtpE
"""

!pip install tensorflow

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from google.colab import drive
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from tensorflow.keras.applications import MobileNetV2

# 1. Monter le Google Drive
drive.mount('/content/drive')

# 2. Définir les chemins selon ton arborescence
base_path = '/content/drive/MyDrive/Collect de données UE projet /videos_preprocessed_8fps'
emotions = ['Desengagement', 'Confusion', 'Neutre']
label_map = {emotion: i for i, emotion in enumerate(emotions)}

file_paths = []
labels = []

# Parcourir les dossiers d'émotions
for emotion in emotions:
    folder_path = os.path.join(base_path, emotion)
    if os.path.exists(folder_path):
        for file_name in os.listdir(folder_path):
            if file_name.endswith('.npy'):
                file_paths.append(os.path.join(folder_path, file_name))
                labels.append(label_map[emotion])
    else:
        print(f"Attention : Le dossier {emotion} est introuvable à l'adresse {folder_path}")

# 3. Séparation des données (Train 80%, Val 10%, Test 10%)
train_paths, test_paths, train_labels, test_labels = train_test_split(
    file_paths, labels, test_size=0.2, random_state=42, stratify=labels
)
val_paths, test_paths, val_labels, test_labels = train_test_split(
    test_paths, test_labels, test_size=0.5, random_state=42, stratify=test_labels
)

print(f"Total vidéos: {len(file_paths)} | Train: {len(train_paths)} | Val: {len(val_paths)} | Test: {len(test_paths)}")

class EmotionDataGenerator(tf.keras.utils.Sequence):
    def __init__(self, file_paths, labels, batch_size=8, num_frames=20, img_size=224, shuffle=True, **kwargs):
        # Correction du Warning : on appelle le constructeur parent avec les kwargs
        super().__init__(**kwargs)
        self.file_paths = file_paths
        self.labels = labels
        self.batch_size = batch_size
        self.num_frames = num_frames
        self.img_size = img_size
        self.shuffle = shuffle
        self.on_epoch_end()

    def __len__(self):
        return int(np.floor(len(self.file_paths) / self.batch_size))

    def __getitem__(self, index):
        indexes = self.indexes[index * self.batch_size:(index + 1) * self.batch_size]
        batch_files = [self.file_paths[k] for k in indexes]
        batch_labels = [self.labels[k] for k in indexes]

        X_list = []
        for f in batch_files:
            video_data = np.load(f) # Chargement du tenseur

            # --- Correction de la dimension temporelle (frames) ---
            # Si trop de frames, on coupe. Si pas assez, on complète par la dernière frame.
            if video_data.shape[0] > self.num_frames:
                video_data = video_data[:self.num_frames]
            elif video_data.shape[0] < self.num_frames:
                padding = np.repeat(video_data[-1:], self.num_frames - video_data.shape[0], axis=0)
                video_data = np.concatenate([video_data, padding], axis=0)

            # --- Correction de la dimension spatiale (résolution) ---
            # Au cas où une frame n'est pas en 224x224
            if video_data.shape[1:3] != (self.img_size, self.img_size):
                resized_video = []
                for frame in video_data:
                    resized_video.append(cv2.resize(frame, (self.img_size, self.img_size)))
                video_data = np.array(resized_video)

            X_list.append(video_data)

        X = np.array(X_list)
        y = tf.keras.utils.to_categorical(batch_labels, num_classes=3)
        return X, y

    def on_epoch_end(self):
        self.indexes = np.arange(len(self.file_paths))
        if self.shuffle:
            np.random.shuffle(self.indexes)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import TimeDistributed, Conv2D, MaxPooling2D, Flatten, Dense, LSTM, GRU, Dropout, GlobalAveragePooling2D
from tensorflow.keras.applications import MobileNetV2

def build_model(model_type="CNN_LSTM", num_frames=20, img_size=224):
    # On définit l'entrée proprement (Nombre de frames, Hauteur, Largeur, Couleurs)
    input_layer = layers.Input(shape=(num_frames, img_size, img_size, 3))

    base_cnn = MobileNetV2(weights='imagenet', include_top=False, input_shape=(img_size, img_size, 3))
    base_cnn.trainable = False

    # Utilisation de l'API Fonctionnelle de Keras (plus propre)
    x = layers.TimeDistributed(base_cnn)(input_layer)
    x = layers.TimeDistributed(layers.GlobalAveragePooling2D())(x)

    if model_type == "CNN_LSTM":
        x = layers.LSTM(64)(x)
    elif model_type == "CNN_GRU":
        x = layers.GRU(64)(x)
    else:
        x = layers.Flatten()(x)
        x = layers.Dense(64, activation='relu')(x)

    x = layers.Dropout(0.5)(x)
    output_layer = layers.Dense(3, activation='softmax')(x)

    model = models.Model(inputs=input_layer, outputs=output_layer, name=model_type)
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# On définit ici les variables train_gen et val_gen
train_gen = EmotionDataGenerator(train_paths, train_labels, batch_size=8)
val_gen = EmotionDataGenerator(val_paths, val_labels, batch_size=8)
test_gen = EmotionDataGenerator(test_paths, test_labels, batch_size=8, shuffle=False)

print("Générateurs créés avec succès !")

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Initialisation du modèle choisi (exemple avec LSTM)
my_model = build_model("CNN_LSTM")

# Callbacks pour éviter le sur-apprentissage et sauvegarder le meilleur résultat
callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ModelCheckpoint('best_emotion_model.h5', save_best_only=True)
]

# Lancement de l'entraînement
history = my_model.fit(
    train_gen, # Ton générateur de données défini précédemment
    validation_data=val_gen,
    epochs=30,
    callbacks=callbacks
)

import matplotlib.pyplot as plt

def plot_history(history):
    acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    epochs = range(1, len(acc) + 1)

    plt.figure(figsize=(12, 5))

    # Graphique de l'Accuracy
    plt.subplot(1, 2, 1)
    plt.plot(epochs, acc, 'b', label='Entraînement')
    plt.plot(epochs, val_acc, 'r', label='Validation')
    plt.title('Précision (Accuracy)')
    plt.legend()

    # Graphique de la Perte (Loss)
    plt.subplot(1, 2, 2)
    plt.plot(epochs, loss, 'b', label='Entraînement')
    plt.plot(epochs, val_loss, 'r', label='Validation')
    plt.title('Perte (Train Loss)')
    plt.legend()
    plt.show()

plot_history(history)

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

def final_validation(model, generator, labels):
    # 1. Prédiction
    predictions = model.predict(generator)
    y_pred = np.argmax(predictions, axis=1)

    # Ajustement des labels réels à la taille des prédictions (batch size)
    y_true = labels[:len(y_pred)]

    # 2. Rapport détaillé (Precision, Recall, F1)
    print("\n--- Rapport de Classification ---")
    print(classification_report(y_true, y_pred, target_names=['Désengagement', 'Confusion', 'Neutre']))

    # 3. Matrice de Confusion (pour voir où le modèle se trompe)
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', xticklabels=emotions, yticklabels=emotions)
    plt.xlabel('Prédiction')
    plt.ylabel('Réalité')
    plt.title('Matrice de Confusion')
    plt.show()

final_validation(my_model, test_gen, test_labels)