# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QHXrYy2Gzypm1fgU-2dZ2sIGbL1gH_M
"""

# ============================================
# PRÉTRAITEMENT DES VIDÉOS - VERSION 4 FPS
# ============================================

!pip install opencv-python-headless mediapipe tqdm

from google.colab import drive
drive.mount('/content/drive')

!pip3 install mediapipe
# ============================================
# IMPORTS
# ============================================
import cv2
import os
import numpy as np
import mediapipe as mp
from tqdm import tqdm
from pathlib import Path
import pandas as pd

CONFIG = {
    # Chemins réels
    "base_dir": "/content/drive/MyDrive/Collect de données UE projet ",
    "input_dir": "/content/drive/MyDrive/Collect de données UE projet /Deuxieme_collecte",
    "output_dir": "/content/drive/MyDrive/Collect de données UE projet /videos_preprocessed_8fps",
    "metadata_path": "/content/drive/MyDrive/Collect de données UE projet /donnees.csv",

    # Sous-dossiers d'émotions
    "emotion_folders": ["Confusion", "Desengagement", "Neutre"],

    # Paramètres d'extraction
    "target_fps": 8,              # 4 frames par seconde
    "target_size": (224, 224),    # Taille pour CNN
    "max_frames_per_video": 400,  # 45s × 4 = 180, sécurité à 200

    # Détection faciale
    "face_detection": True,
    "face_margin": 0.2,

    # Format de sortie
    "output_format": "npy",
}

# ============================================
# CHARGEMENT DES MÉTADONNÉES (FILTRE PHASE 2)
# ============================================
def load_phase2_metadata(config):
    """Charge uniquement les lignes de la phase 2 depuis donnees.csv"""
    df = pd.read_csv(config["metadata_path"])

    # Filtrer pour garder uniquement la phase 2
    df_phase2 = df[df["phase"] == "phase_2"].copy()

    print(f"Métadonnées chargées:")
    print(f"   - Total lignes: {len(df)}")
    print(f"   - Phase 2: {len(df_phase2)}")
    print(f"   - Distribution émotions (phase 2):")
    for emotion in CONFIG["emotion_folders"]:
        count = len(df_phase2[df_phase2["emotion"] == emotion.lower()])
        print(f"      * {emotion}: {count}")

    return df_phase2

"""* CLASSE DE PRÉTRAITEMENT

"""

class VideoPreprocessor:
    def __init__(self, config):
        self.config = config
        print("Préprocesseur initialisé (sans détection faciale)")

    def extract_frames_from_video(self, video_path):
        """Extrait les frames à 4 fps"""
        cap = cv2.VideoCapture(video_path)

        if not cap.isOpened():
            return np.array([])

        original_fps = cap.get(cv2.CAP_PROP_FPS)
        if original_fps <= 0:
            original_fps = 30

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        duration = total_frames / original_fps

        target_frame_count = min(
            self.config["max_frames_per_video"],
            int(duration * self.config["target_fps"])
        )

        if target_frame_count <= 0:
            target_frame_count = 30

        frames = []

        # Méthode plus simple: prendre des frames à intervalle régulier
        frame_interval = max(1, int(original_fps / self.config["target_fps"]))

        frame_count = 0
        while len(frames) < target_frame_count and frame_count < total_frames:
            cap.set(cv2.CAP_PROP_POS_FRAMES, frame_count)
            ret, frame = cap.read()

            if not ret:
                break

            # Redimensionnement direct (sans détection faciale)
            frame_resized = cv2.resize(frame, self.config["target_size"])
            frame_rgb = cv2.cvtColor(frame_resized, cv2.COLOR_BGR2RGB)
            frames.append(frame_rgb)

            frame_count += frame_interval

        cap.release()

        # Padding si nécessaire
        if len(frames) < target_frame_count and len(frames) > 0:
            last_frame = frames[-1]
            while len(frames) < target_frame_count:
                frames.append(last_frame.copy())

        if len(frames) == 0:
            return np.array([])

        return np.array(frames, dtype=np.uint8)

    def process_all_videos(self):
        """Parcourt les dossiers"""
        stats = {
            "total_videos": 0,
            "processed": 0,
            "failed": 0,
            "total_frames": 0,
            "frames_per_video": [],
            "by_emotion": {}
        }

        for emotion_folder in self.config["emotion_folders"]:
            emotion_path = Path(self.config["input_dir"]) / emotion_folder
            output_emotion_dir = Path(self.config["output_dir"]) / emotion_folder

            if not emotion_path.exists():
                print(f"Dossier non trouvé: {emotion_path}")
                continue

            os.makedirs(output_emotion_dir, exist_ok=True)

            video_files = list(emotion_path.glob("*.mp4")) + \
                         list(emotion_path.glob("*.MP4")) + \
                         list(emotion_path.glob("*.avi")) + \
                         list(emotion_path.glob("*.mov"))

            print(f"\nDossier {emotion_folder}: {len(video_files)} vidéos trouvées")

            stats["by_emotion"][emotion_folder] = {
                "found": len(video_files),
                "processed": 0,
                "failed": 0,
                "frames": 0
            }

            for video_path in tqdm(video_files, desc=f"Traitement {emotion_folder}"):
                stats["total_videos"] += 1

                output_filename = video_path.stem + ".npy"
                output_path = output_emotion_dir / output_filename

                if output_path.exists():
                    stats["processed"] += 1
                    stats["by_emotion"][emotion_folder]["processed"] += 1
                    continue

                try:
                    frames = self.extract_frames_from_video(str(video_path))

                    if len(frames) > 0:
                        np.save(str(output_path), frames)
                        stats["processed"] += 1
                        stats["total_frames"] += len(frames)
                        stats["frames_per_video"].append(len(frames))
                        stats["by_emotion"][emotion_folder]["processed"] += 1
                        stats["by_emotion"][emotion_folder]["frames"] += len(frames)
                    else:
                        stats["failed"] += 1
                        stats["by_emotion"][emotion_folder]["failed"] += 1

                except Exception as e:
                    print(f"Erreur {video_path.name}: {e}")
                    stats["failed"] += 1
                    stats["by_emotion"][emotion_folder]["failed"] += 1

        return stats

"""* FONCTION POUR LIER MÉTADONNÉES"""

def create_aligned_metadata(config, preprocess_stats):
    """Crée un fichier CSV alignant les vidéos traitées avec leurs métadonnées"""
    df_metadata = pd.read_csv(config["metadata_path"])
    df_phase2 = df_metadata[df_metadata["phase"] == "phase_2"].copy()

    all_videos = []

    for emotion_folder in CONFIG["emotion_folders"]:
        emotion_dir = Path(config["output_dir"]) / emotion_folder
        if not emotion_dir.exists():
            continue

        npy_files = list(emotion_dir.glob("*.npy"))

        for npy_path in npy_files:
            filename = npy_path.stem
            frames = np.load(str(npy_path))
            n_frames = frames.shape[0]

            matching_rows = df_phase2[df_phase2["filename"] == filename]

            if len(matching_rows) > 0:
                meta = matching_rows.iloc[0].to_dict()
            else:
                meta = {}

            all_videos.append({
                "filename": filename,
                "path": str(npy_path),
                "emotion_folder": emotion_folder,
                "n_frames": n_frames,
                "age": meta.get("age", None),
                "sexe": meta.get("sexe", None),
                "lunettes": meta.get("port_lunettes", None),
                "teint": meta.get("teint", None),
                "niveau_concentration": meta.get("niveau_concentration", None),
                "emotion_ciblee": meta.get("emotion", emotion_folder.lower())
            })

    df_aligned = pd.DataFrame(all_videos)
    output_csv = Path(config["output_dir"]) / "metadata_aligned.csv"
    df_aligned.to_csv(output_csv, index=False)

    print(f"\nMétadonnées alignées: {output_csv}")
    print(f"   Total vidéos: {len(df_aligned)}")
    print(df_aligned["emotion_folder"].value_counts())

    return df_aligned

"""* EXÉCUTION PRINCIPALE"""

print("="*60)
print("PRÉTRAITEMENT VIDÉOS")
print("="*60)

print("\nVérification de la structure...")
base_path = Path(CONFIG["base_dir"])
collecte_path = Path(CONFIG["input_dir"])

print(f"Dossier base: {base_path.exists()}")
print(f"Dossier collecte: {collecte_path.exists()}")

for folder in CONFIG["emotion_folders"]:
    folder_path = collecte_path / folder
    print(f"   - {folder}: {folder_path.exists()}")

# Créer le dossier de sortie
os.makedirs(CONFIG["output_dir"], exist_ok=True)

# Lancer le prétraitement
print(f"\nDémarrage du prétraitement (target_fps={CONFIG['target_fps']})...")
preprocessor = VideoPreprocessor(CONFIG)
stats = preprocessor.process_all_videos()

# Afficher le rapport
print("\n" + "="*60)
print("RAPPORT FINAL DE PRÉTRAITEMENT")
print("="*60)
print(f"Total vidéos trouvées: {stats['total_videos']}")
print(f"Traitées avec succès: {stats['processed']}")
print(f"Échecs: {stats['failed']}")
print(f"Total frames extraites: {stats['total_frames']}")
if stats['processed'] > 0:
    print(f"Moyenne frames/vidéo: {stats['total_frames']/stats['processed']:.1f}")

print("\nPar émotion:")
for emotion, data in stats["by_emotion"].items(matrice):
    if data['found'] > 0:
        print(f"   {emotion}: {data['processed']}/{data['found']} vidéos, {data['frames']} frames")

# Créer les métadonnées alignées
print("\nAlignement des métadonnées...")
df_aligned = create_aligned_metadata(CONFIG, stats)

# Vérification finale
print("\nVérification des fichiers générés:")
output_path = Path(CONFIG["output_dir"])
npy_files = list(output_path.rglob("*.npy"))
print(f"   Total fichiers .npy: {len(npy_files)}")
if len(npy_files) > 0:
    sample = np.load(npy_files[0])
    print(f"   Shape exemple: {sample.shape}")
    print(f"   dtype: {sample.dtype}")

print("\nPRÉTRAITEMENT TERMINÉ !")
print(f"Dossier de sortie: {CONFIG['output_dir']}")

# Pour identifier les vidéos problématiques
import cv2
from pathlib import Path

confusion_dir = Path("/content/drive/MyDrive/Collecte_UE_Projet/Deuxieme_collecte/Confusion")
for video in confusion_dir.glob("*.mp4"):
    cap = cv2.VideoCapture(str(video))
    if not cap.isOpened():
        print(f"Corrompue: {video.name}")
    else:
        fps = cap.get(cv2.CAP_PROP_FPS)
        frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        duration = frames/fps if fps>0 else 0
        if duration < 1:
            print(f"Trop courte ({duration:.1f}s): {video.name}")
    cap.release()

# Retraitement des vidéos Confusion échouées
failed_videos = []

confusion_dir = Path(CONFIG["input_dir"]) / "Confusion"
output_dir = Path(CONFIG["output_dir"]) / "Confusion"

for video in confusion_dir.glob("*.mp4"):
    output_path = output_dir / (video.stem + ".npy")
    if not output_path.exists():
        failed_videos.append(video)

print(f"Vidéos à retraiter: {len(failed_videos)}")

# Retraiter avec plus de tolérance
for video in tqdm(failed_videos):
    try:
        cap = cv2.VideoCapture(str(video))
        if not cap.isOpened():
            print(f"Impossible: {video.name}")
            continue

        # Extraction forcée
        frames = []
        frame_count = 0
        while True:
            ret, frame = cap.read()
            if not ret:
                break
            if frame_count % 15 == 0:  # 2 fps si 30 fps original
                frame = cv2.resize(frame, (224, 224))
                frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                frames.append(frame_rgb)
            frame_count += 1

        cap.release()

        if len(frames) > 0:
            np.save(str(output_dir / (video.stem + ".npy")), np.array(frames))
            print(f"{video.name}: {len(frames)} frames")
    except Exception as e:
        print(f"{video.name}: {e}")